// Sign In
export const SIGN_IN_LOADING = 'SIGN_IN_LOADING';
export const SIGN_IN_FALIURE = 'SIGN_IN_FALIURE';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_RESET_STATES = 'SIGN_IN_RESET_STATES';


// Overview

export const GET_OVERVIEW_LOADING = 'GET_OVERVIEW_LOADING';
export const GET_OVERVIEW_FALIURE = 'GET_OVERVIEW_FALIURE';
export const GET_OVERVIEW_SUCCESS = 'GET_OVERVIEW_SUCCESS';
export const GET_OVERVIEW_RESET_STATES = 'GET_OVERVIEW_RESET_STATES';

// Create feedback

export const CREATE_FEEDBACK_LOADING='CREATE_FEEDBACK_LOADING';
export const CREATE_FEEDBACK_FALIURE='CREATE_FEEDBACK_FALIURE';
export const CREATE_FEEDBACK_SUCCESS='CREATE_FEEDBACK_SUCCESS';
export const CREATE_FEEDBACK_RESET_STATES='CREATE_FEEDBACK_RESET_STATES';